name: Python Package using Conda

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniconda-version: 'latest'
        environment-file: environment.yml
        python-version: '3.10'

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda run -n base pip install -r requirements.txt || conda run -n base conda install --file requirements.txt

    - name: Lint with flake8
      run: |
        conda run -n base pip install flake8
        conda run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda run -n base pip install pytest
        conda run -n base pytest

